# config.yaml
grid_size: 8
num_features: 3
centroids:
  - [2, 3]
  - [1, 5]
  - [4,5]
sigmas: [0.5, 0.5, 0.5]
num_theta_values: 2
gamma: 0.9
horizon: 4

human_actions:
  - [0, 0]
  - [-1, 0]
  - [1, 0]
  - [0, -1]
  - [0, 1]
robot_actions:
  - [0, 0]
  - [-1, 0]
  - [1, 0]
  - [0, -1]
  - [0, 1]
